services:
  users-migrator:
    build:
      target: builder

  notifier-migrator:
    build:
      target: builder

  users:
    build:
      target: builder
    command: sh -c "npm run build:libs && cd apps/users && npx nest start --watch"
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: 'true'
    volumes:
      - ./apps/users/src:/app/apps/users/src
      - ./apps/users/tsconfig.json:/app/apps/users/tsconfig.json
      - ./apps/users/nest-cli.json:/app/apps/users/nest-cli.json
      - ./libs:/app/libs
      - /app/node_modules
      - /app/apps/users/node_modules

  notifier:
    build:
      target: builder
    command: sh -c "npm run build:libs && cd apps/notifier && npx nest start --watch"
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: 'true'
    volumes:
      - ./apps/notifier/src:/app/apps/notifier/src
      - ./apps/notifier/tsconfig.json:/app/apps/notifier/tsconfig.json
      - ./apps/notifier/nest-cli.json:/app/apps/notifier/nest-cli.json
      - ./libs:/app/libs
      - /app/node_modules
      - /app/apps/notifier/node_modules

  scheduler:
    build:
      target: builder
    command: sh -c "npm run build:libs && cd apps/scheduler && npx nest start --watch"
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: 'true'
    volumes:
      - ./apps/scheduler/src:/app/apps/scheduler/src
      - ./apps/scheduler/tsconfig.json:/app/apps/scheduler/tsconfig.json
      - ./apps/scheduler/nest-cli.json:/app/apps/scheduler/nest-cli.json
      - ./libs:/app/libs
      - /app/node_modules
      - /app/apps/scheduler/node_modules
